const myStr = "FirstLine\n\t\\SecondLine\nThirdLine"; // Change this line
//------------------------------------------------------------------------------------------------
const myStr1 = "This is the start. " + "This is the end."; // Change this line
// ------------------------------------------------------------------------------------------------
let myStr2 = "This is the first sentence. ";
myStr2 += "This is the second sentence.";
// ------------------------------------------------------------------------------------------------
// Only change code below this line
const myName = "Jay Boricha";
const myStr3 = "My name is" + myName + "and I am well!";
// ------------------------------------------------------------------------------------------------
// Change code below this line
const someAdjective = "joke!";
let myStr4 = "Learning to code is ";
myStr4 += someAdjective;
// ------------------------------------------------------------------------------------------------
// Setup
let lastNameLength = 0;
const lastName = "Lovelace";

// Only change code below this line
lastNameLength = lastName.length;
// ------------------------------------------------------------------------------------------------
// Setup
let firstLetterOfLastName = "";
const lastName1 = "Lovelace";

// Only change code below this line
firstLetterOfLastName = lastName1[0]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
let myStr5 = "Jello World";

// Only change code below this line
myStr = "Hello World"; // Change this line
// Only change code above this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName2 = "Lovelace";

// Only change code below this line
const thirdLetterOfLastName = lastName[2]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName3 = "Lovelace";

// Only change code below this line
const lastLetterOfLastName = lastName3[lastName.length - 1]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName4 = "Lovelace";

// Only change code below this line
const secondToLastLetterOfLastName = lastName[lastName.length-2]; // Change this line
// ------------------------------------------------------------------------------------------------