const myStr = "FirstLine\n\t\\SecondLine\nThirdLine"; // Change this line
//------------------------------------------------------------------------------------------------
const myStr1 = "This is the start. " + "This is the end."; // Change this line
// ------------------------------------------------------------------------------------------------
let myStr2 = "This is the first sentence. ";
myStr2 += "This is the second sentence.";
// ------------------------------------------------------------------------------------------------
// Only change code below this line
const myName = "Jay Boricha";
const myStr3 = "My name is" + myName + "and I am well!";
// ------------------------------------------------------------------------------------------------
// Change code below this line
const someAdjective = "joke!";
let myStr4 = "Learning to code is ";
myStr4 += someAdjective;
// ------------------------------------------------------------------------------------------------
// Setup
let lastNameLength = 0;
const lastName = "Lovelace";

// Only change code below this line
lastNameLength = lastName.length;
// ------------------------------------------------------------------------------------------------
// Setup
let firstLetterOfLastName = "";
const lastName1 = "Lovelace";

// Only change code below this line
firstLetterOfLastName = lastName1[0]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
let myStr5 = "Jello World";

// Only change code below this line
myStr = "Hello World"; // Change this line
// Only change code above this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName2 = "Lovelace";

// Only change code below this line
const thirdLetterOfLastName = lastName[2]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName3 = "Lovelace";

// Only change code below this line
const lastLetterOfLastName = lastName3[lastName.length - 1]; // Change this line
// ------------------------------------------------------------------------------------------------
// Setup
const lastName4 = "Lovelace";

// Only change code below this line
const secondToLastLetterOfLastName = lastName[lastName.length-2]; // Change this line
// ------------------------------------------------------------------------------------------------
var myNoun = "dog";
var myAdjective = "big";
var myVerb = "ran";
var myAdverb = "quickly";

var wordBlanks = "The " + myAdjective + " " + myNoun + " " + myVerb + " " + myAdverb + "."; // Only change this line;
// ------------------------------------------------------------------------------------------------

//initialized array
// Only change code below this line
const myArraya= ["Jay" , 7];
// ------------------------------------------------------------------------------------------------

// Only change code below this line
const myArrayb = [["Jay" , "7"], ["Krutik" , "30"]];
// ------------------------------------------------------------------------------------------------
const myArrayc = [50, 60, 70];
const myData = myArray[0]
// ------------------------------------------------------------------------------------------------
// Setup
const myArrayd = [18, 64, 99];

// Only change code below this line
myArray[0] = 45
// ------------------------------------------------------------------------------------------------
const myArraye = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [[10, 11, 12], 13, 14],
  ];
//   ------------------------------------------------------------------------------------------------
  const myDataf = myArray[2][1];

  // Setup
const myArrayf = [["John", 23], ["cat", 2]];

// Only change code below this line
myArray.push(["dog", 3])
// ------------------------------------------------------------------------------------------------
// Setup
const myArrayg = [["John", 23], ["cat", 2]];

// Only change code below this line
const removedFromMyArray = myArray.pop();
// ------------------------------------------------------------------------------------------------
// Setup
const myArray = [["John", 23], ["dog", 3]];

// Only change code below this line
const removedFromMyArray1 = myArray.shift()
// ------------------------------------------------------------------------------------------------